version: "3.7"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '1'
#    volumes:
#      -  ./mysql-data5_7:/var/lib/mysql
    ports:
      - 3307:3306
